__author__ = 'hoangphuong'


class ANIMATION_ACTIONS:
    SHOW_CAMERA = 'SHOW_CAMERA'
    HIDE_CAMERA = 'HIDE_CAMERA'
    SHOW_CARD = 'SHOW_CARD'
    HIDE_CARD = 'HIDE_CARD'
    NORMAL = 'NORMAL'
    HAPPY = "HAPPY"
    SMILE = "SMILE"
    BLINK = "BLINK"
    LAUGHING = "LAUGHING"
    SHAKE = "SHAKE"
    SURPRISE = "SURPRISE"
    THINKING = "THINKING"
    CRYING = "CRYING"
    TALK = "TALK"
    LISTEN = "LISTEN"





